# Generated by Django 2.1 on 2021-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_dt', models.CharField(max_length=10)),
                ('cy_name', models.CharField(max_length=50)),
                ('confirm', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('today_confirm', models.IntegerField()),
                ('today_new_confirm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_dt', models.CharField(max_length=10)),
                ('cy_name', models.CharField(max_length=50)),
                ('prov_name', models.CharField(max_length=50)),
                ('confirm', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('today_confirm', models.IntegerField()),
                ('today_new_confirm', models.IntegerField()),
            ],
        ),
    ]
